FROM ubuntu:24.04

RUN apt update -q && apt install -y python3 git curl wget nodejs npm

RUN curl -LsSf https://astral.sh/uv/install.sh | sh

ENV PATH=$PATH:/root/.local/bin

WORKDIR /opt
ADD https://api.github.com/repos/muka/mcp-proxy-server/git/refs/heads/main version.json
RUN git clone https://github.com/muka/mcp-proxy-server
RUN cd ./mcp-proxy-server && npm i && npm run build

WORKDIR /opt/mcp-proxy-server

ENTRYPOINT [ "node" ]
CMD [ "build/sse.js" ]