version: '3'

tasks:
  qdrant-start:
    deps: [qdrant-stop]
    cmds:
      - docker run -d --rm --name qdrant1 -p 6333:6333 qdrant/qdrant
  qdrant-stop:
    cmds:
      - docker stop qdrant1 || true

  stop:
    cmds:
      - task: mcp-stop
      - task: runtimes-stop
      - docker compose down

  dev:
    cmds:
      - docker compose kill runtime || true
      - docker compose rm -f runtime  || true
      - docker compose run --rm -it runtime run dev {{.CLI_ARGS}}

  bash:
    cmds:
      - docker compose run --rm -it --entrypoint bash runtime

  build:
    cmds:
      - docker compose build

  mcp-build-proxy-base:
    cmds:     
      - docker build ./mcp/mcp-proxy-base -f ./mcp/mcp-proxy-base/Dockerfile -t mcp-proxy/base

  mcp-build-servers-base:
    deps: [mcp-build-proxy-base]
    cmds:     
      - docker build ./mcp/mcp-servers -f ./mcp/mcp-servers/Dockerfile.base -t mcp-proxy/servers-base

  mcp-build:
    deps: [mcp-build-servers-base]
    cmds:     
      - docker compose -f docker-compose.mcp.yaml build {{.CLI_ARGS}}

  mcp-run:
    deps: [mcp-stop]
    cmds:
      - docker compose -f docker-compose.mcp.yaml up -d {{.CLI_ARGS}}
      - docker compose -f docker-compose.mcp.yaml logs -f {{.CLI_ARGS}}

  mcp-stop:
    cmds:
      - docker compose -f docker-compose.mcp.yaml kill {{.CLI_ARGS}} || true
      - docker compose -f docker-compose.mcp.yaml rm -f {{.CLI_ARGS}} || true

  runtimes-mlc-build:
    cmds:
      - docker compose -f docker-compose.runtimes.yaml build mlc

  runtimes-stop:
    cmds:
      - docker compose -f docker-compose.runtimes.yaml down

  runtimes-start-mlc:
    deps: [ runtimes-stop ]
    cmds:
      - docker compose -f docker-compose.runtimes.yaml up -d mlc
      - docker compose -f docker-compose.runtimes.yaml logs -f mlc

  runtimes-start-vllm:
    deps: [ runtimes-stop ]
    cmds:
      - docker compose -f docker-compose.runtimes.yaml up -d vllm
      - docker compose -f docker-compose.runtimes.yaml logs -f vllm

  runtimes-start-ollama:
    deps: [ runtimes-stop ]
    cmds:
      - docker compose -f docker-compose.runtimes.yaml up -d ollama
      - docker compose -f docker-compose.runtimes.yaml logs -f ollama

  runtimes-ollama-pull-images:
    cmds:
      - task runtimes-ollama-pull-image -- hermes3
      - task runtimes-ollama-pull-image -- smallthinker
      - task runtimes-ollama-pull-image -- llama3.2
      - task runtimes-ollama-pull-image -- llama3.1:8b
      - task runtimes-ollama-pull-image -- mistral:8b

  runtimes-ollama-pull-image:
    cmds:
      - docker compose -f docker-compose.runtimes.yaml exec ollama ollama pull {{.CLI_ARGS}}
  