FROM mcp-proxy/base

WORKDIR /app
RUN git clone https://github.com/modelcontextprotocol/servers
RUN cd servers/src/github && npm i && npm run build

WORKDIR /app/servers/src/github
ENV COMMAND="node dist/index.js"