FROM mcp-proxy/base

WORKDIR /app
RUN git clone https://github.com/modelcontextprotocol/servers
RUN cd servers/src/filesystem && npm i && npm run build

ENV COMMAND="node /app/servers/src/filesystem/dist/index.js /data"