
mcp:
  - name: search
    type: sse
    url: http://web-search/sse
  - name: fs
    type: sse
    url: http://filesystem/sse
  - name: git
    type: sse
    url: http://git/sse
  - name: arxiv
    type: sse
    url: http://arxiv/sse
  - name: fetch
    type: sse
    url: http://fetch/sse
  - name: mem
    type: sse
    url: http://memory/sse

tasks: 
  - task: 
      write the code to create a web-based todo list. Use Svelte Kit for the frontend. Use Nest.js for the backend API. 
      Ensure the filesystem is kept in sync during the execution of each step. Create and mantain a git repository while applying edits.
    agents: 
      - architect
      - developer
      - reviewer
      - tester
      - devops
      - executor
    color: blue

agents:
  - name: architect
    role: software architect
    capabilities: defines the architecture and provide the implementation steps based on best practices
    color: green

  - name: developer
    role: software developer
    capabilities: write high-quality, documented and performant code.
    color: red

  - name: reviewer
    role: code reviewer
    capabilities: carefully review and evaluate code to report improvements
    color: magenta
 
  - name: tester
    role: software tester
    capabilities: develop tests based on code and evaluate the quality of response.
    color: orange

  - name: devops
    role: dev ops
    capabilities: create a docker based deployment. Creates the Dockerfile and the integrated docker compose for the required services
    color: yellow

  - name: executor
    role: filesystem executor
    capabilities: 
      Handle interaction with the codebase on the filesystem. 
      Check existing directory structure and format paths properly.
    color: red
    # tools: 
    #   - read_file
    #   - write_file
    #   - create_directory
    #   - list_directory
    #   - search_files
    #   - get_file_info


